import { useEffect, useState, useContext } from 'react';
import { getProjectTasks, createTask, updateTaskStatus, deleteTask, generateTasksWithAI, editTask } from '../services/taskService';
import { CheckCircle2, Circle, Clock, Plus, Trash2, EyeOff, Eye, Sparkles, Loader2, Edit2 } from 'lucide-react';
import toast from 'react-hot-toast';
import Skeleton from './Skeleton';
import { AuthContext } from '../context/authContext';

const Tasks = ({ projectId, members = [] }) => {
    const { user } = useContext(AuthContext);
    const [tasks, setTasks] = useState([]);
    const [isAdding, setIsAdding] = useState(false);
    const [isLoading, setIsLoading] = useState(true);
    const [showCompleted, setShowCompleted] = useState(true);
    const [newTask, setNewTask] = useState({ title: '', description: '', priority: 'Medium', assignedTo: '' });
    const [animatingTask, setAnimatingTask] = useState(null);

    // AI Auto-Task States
    const [isAutoGenerating, setIsAutoGenerating] = useState(false);
    const [autoGoal, setAutoGoal] = useState('');
    const [isAIThinking, setIsAIThinking] = useState(false);

    // Edit Task States
    const [editingTask, setEditingTask] = useState(null);
    const [editFormData, setEditFormData] = useState({ title: '', description: '', priority: '', assignedTo: '' });

    const fetchTasks = async () => {
        try {
            const data = await getProjectTasks(projectId);
            setTasks(data);
        } catch (error) {
            toast.error("Failed to load tasks");
        } finally {
            setIsLoading(false);
        }
    };

    useEffect(() => { fetchTasks(); }, [projectId]);

    const handleCreate = async (e) => {
        e.preventDefault();
        try {
            await createTask(projectId, { ...newTask, project: projectId });
            setIsAdding(false);
            setNewTask({ title: '', description: '', priority: 'Medium', assignedTo: '' });
            fetchTasks();
            toast.success("Task added");
        } catch (err) {
            toast.error(err.response?.data?.message || "Failed to create task");
        }
    };

    const handleAutoGenerate = async (e) => {
        e.preventDefault();
        setIsAIThinking(true);
        try {
            const aiTasks = await generateTasksWithAI(autoGoal);

            // Sequentially create each task generated by AI
            for (const t of aiTasks) {
                await createTask(projectId, {
                    title: t.title,
                    description: t.description,
                    priority: t.priority || 'Medium',
                    assignedTo: user._id,
                    project: projectId
                });
            }

            setIsAutoGenerating(false);
            setAutoGoal('');
            fetchTasks(); // Refresh to show the new tasks
            toast.success(`Successfully generated ${aiTasks.length} tasks!`, { icon: '🤖' });
        } catch (err) {
            toast.error(err.response?.data?.message || "Failed to generate tasks using AI");
        } finally {
            setIsAIThinking(false);
        }
    };

    const handleUpdate = async (e) => {
        e.preventDefault();
        try {
            await editTask(editingTask, editFormData);
            setEditingTask(null);
            fetchTasks();
            toast.success("Task updated successfully");
        } catch (err) {
            toast.error(err.response?.data?.message || "Failed to update task");
        }
    };

    const handleToggleStatus = async (task) => {
        const newStatus = task.status === 'Done' ? 'To-Do' : 'Done';

        // Optimistic UI update + animation trigger
        if (newStatus === 'Done') setAnimatingTask(task._id);

        setTasks(prev => prev.map(t => t._id === task._id ? { ...t, status: newStatus } : t));

        try {
            await updateTaskStatus(task._id, newStatus);
            if (newStatus === 'Done') {
                toast.success("Task completed!", { icon: '🎉' });
                setTimeout(() => setAnimatingTask(null), 500); // clear animation state
            }
        } catch (err) {
            toast.error(err.response?.data?.message || "Failed to update status");
            // Revert on failure
            fetchTasks();
            setAnimatingTask(null);
        }
    };

    const handleDelete = async (taskId) => {
        const confirm = window.confirm("Are you sure you want to delete this task?");
        if (!confirm) return;

        // Optimistic Delete
        setTasks(prev => prev.filter(t => t._id !== taskId));

        try {
            await deleteTask(taskId);
            toast.success("Task deleted");
        } catch (err) {
            toast.error(err.response?.data?.message || "Failed to delete task");
            fetchTasks(); // Revert
        }
    };

    const getPriorityColor = (p) => {
        if (p === 'High') return 'text-red-400 bg-red-400/10 border border-red-400/20';
        if (p === 'Medium') return 'text-yellow-400 bg-yellow-400/10 border border-yellow-400/20';
        return 'text-green-400 bg-green-400/10 border border-green-400/20';
    };

    // Sorting: Active tasks first, Done tasks at the bottom
    // Then assigned to current user first
    // Then priority High > Medium > Low
    const priorityWeights = { High: 3, Medium: 2, Low: 1 };

    const sortedTasks = [...tasks].sort((a, b) => {
        // 1. Status
        if (a.status === 'Done' && b.status !== 'Done') return 1;
        if (a.status !== 'Done' && b.status === 'Done') return -1;

        // 2. Assigned to current user
        const aAssignedToMe = a.assignedTo && (a.assignedTo._id === user?._id || a.assignedTo === user?._id);
        const bAssignedToMe = b.assignedTo && (b.assignedTo._id === user?._id || b.assignedTo === user?._id);

        if (aAssignedToMe && !bAssignedToMe) return -1;
        if (!aAssignedToMe && bAssignedToMe) return 1;

        // 3. Priority
        const pA = priorityWeights[a.priority] || 0;
        const pB = priorityWeights[b.priority] || 0;
        if (pA !== pB) return pB - pA; // Descending priority

        // 4. Fallback to newest
        return new Date(b.createdAt) - new Date(a.createdAt);
    });

    const displayTasks = showCompleted ? sortedTasks : sortedTasks.filter(t => t.status !== 'Done');

    if (isLoading) return <Skeleton lines={5} />;

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <div className="flex items-center gap-4">
                    <h3 className="text-xl font-semibold">Project Tasks</h3>
                    <button
                        onClick={() => setShowCompleted(!showCompleted)}
                        className="flex items-center gap-1.5 text-xs font-medium text-gray-500 hover:text-gray-300 transition-colors bg-gray-800/50 px-2 py-1 rounded-md"
                    >
                        {showCompleted ? <><EyeOff size={14} /> Hide Done</> : <><Eye size={14} /> Show Done</>}
                    </button>
                </div>
                <div className="flex gap-2 items-center">
                    <button
                        onClick={() => { setIsAutoGenerating(!isAutoGenerating); setIsAdding(false); }}
                        className="bg-purple-600 hover:bg-purple-700 text-white font-bold px-3 py-2 rounded-lg transition-colors cursor-pointer flex items-center gap-1.5 text-sm shadow-md shadow-purple-900/20"
                        title="Auto-Generate with AI"
                    >
                        <Sparkles size={16} className="text-yellow-300" /> <span className="hidden sm:inline">AI Generate</span>
                    </button>
                    <button
                        onClick={() => { setIsAdding(!isAdding); setIsAutoGenerating(false); }}
                        className="bg-blue-600 hover:bg-blue-700 text-white p-2 rounded-lg transition-colors cursor-pointer shadow-md"
                    >
                        <Plus size={20} />
                    </button>
                </div>
            </div>

            {/* AI Auto-Generate Form */}
            {isAutoGenerating && (
                <form onSubmit={handleAutoGenerate} className="bg-gradient-to-r from-purple-900/30 to-blue-900/20 p-5 rounded-xl border border-purple-500/40 flex flex-col sm:flex-row gap-4 items-end animate-in fade-in slide-in-from-top-4 duration-300 shadow-lg">
                    <div className="flex-1 w-full">
                        <label className="block text-xs font-bold text-purple-300 mb-2 flex items-center gap-1.5 uppercase tracking-wider">
                            <Sparkles size={14} className="text-yellow-400" /> Prompt Gemini Manager
                        </label>
                        <input
                            className="w-full bg-gray-900/80 border border-purple-500/50 rounded-lg px-4 py-3 text-sm outline-none focus:border-purple-400 focus:ring-1 focus:ring-purple-400 text-white placeholder-gray-500 transition-all"
                            placeholder="e.g. Build an authentication system with JWT and password hashing"
                            value={autoGoal}
                            onChange={(e) => setAutoGoal(e.target.value)}
                            required
                        />
                    </div>
                    <button
                        type="submit"
                        disabled={isAIThinking}
                        className="w-full sm:w-auto bg-purple-600 hover:bg-purple-500 px-6 py-3 rounded-lg font-bold text-sm transition-all cursor-pointer flex items-center justify-center gap-2 disabled:opacity-50 shadow-md"
                    >
                        {isAIThinking ? <Loader2 size={18} className="animate-spin text-white" /> : <Sparkles size={18} className="text-yellow-300" />}
                        {isAIThinking ? 'Planning...' : 'Generate Tasks'}
                    </button>
                </form>
            )}

            {/* Quick Add Form */}
            {isAdding && (
                <form onSubmit={handleCreate} className="bg-gray-900/50 p-4 rounded-xl border border-gray-700 flex flex-wrap gap-4 items-end animate-in fade-in slide-in-from-top-4 duration-200">
                    <div className="flex-1 min-w-[200px]">
                        <label className="block text-xs text-gray-500 mb-1">Task Title</label>
                        <input
                            className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm outline-none focus:border-blue-500"
                            placeholder="e.g. Design Database Schema"
                            value={newTask.title}
                            onChange={(e) => setNewTask({ ...newTask, title: e.target.value })}
                            required
                        />
                    </div>
                    <div className="flex-1 min-w-[200px]">
                        <label className="block text-xs text-gray-500 mb-1">Description</label>
                        <input
                            className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm outline-none focus:border-blue-500"
                            placeholder="Brief task description"
                            value={newTask.description}
                            onChange={(e) => setNewTask({ ...newTask, description: e.target.value })}
                            required
                        />
                    </div>
                    <div>
                        <label className="block text-xs text-gray-500 mb-1">Priority</label>
                        <select
                            className="bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm outline-none"
                            value={newTask.priority}
                            onChange={(e) => setNewTask({ ...newTask, priority: e.target.value })}
                        >
                            <option>Low</option>
                            <option>Medium</option>
                            <option>High</option>
                        </select>
                    </div>
                    <div>
                        <label className="block text-xs text-gray-500 mb-1">Assign To</label>
                        <select
                            className="bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm outline-none"
                            value={newTask.assignedTo}
                            onChange={(e) => setNewTask({ ...newTask, assignedTo: e.target.value })}
                            required
                        >
                            <option value="">Select member...</option>
                            {members.map(member => (
                                <option key={member._id} value={member._id}>
                                    {member.name || member.email}
                                </option>
                            ))}
                        </select>
                    </div>
                    <button type="submit" className="bg-blue-600 hover:bg-blue-500 px-6 py-2 rounded-lg font-bold text-sm transition-colors cursor-pointer">Save</button>
                </form>
            )}

            {/* Task List */}
            <div className="grid gap-3">
                {displayTasks.map(task => {
                    const isDone = task.status === 'Done';
                    const isAnimating = animatingTask === task._id;

                    if (editingTask === task._id) {
                        return (
                            <div key={task._id} className="bg-gray-800/80 p-4 rounded-xl border border-blue-500/50 animate-in fade-in zoom-in-95 duration-200">
                                <form onSubmit={handleUpdate} className="flex flex-wrap gap-4 items-end">
                                    <div className="flex-1 min-w-[150px]">
                                        <label className="block text-xs text-gray-400 mb-1">Title</label>
                                        <input
                                            className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm outline-none focus:border-blue-500"
                                            value={editFormData.title}
                                            onChange={(e) => setEditFormData({ ...editFormData, title: e.target.value })}
                                            required
                                        />
                                    </div>
                                    <div className="flex-1 min-w-[200px]">
                                        <label className="block text-xs text-gray-400 mb-1">Description</label>
                                        <input
                                            className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm outline-none focus:border-blue-500"
                                            value={editFormData.description}
                                            onChange={(e) => setEditFormData({ ...editFormData, description: e.target.value })}
                                            required
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-xs text-gray-400 mb-1">Priority</label>
                                        <select
                                            className="bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm outline-none"
                                            value={editFormData.priority}
                                            onChange={(e) => setEditFormData({ ...editFormData, priority: e.target.value })}
                                        >
                                            <option>Low</option>
                                            <option>Medium</option>
                                            <option>High</option>
                                        </select>
                                    </div>
                                    <div>
                                        <label className="block text-xs text-gray-400 mb-1">Assign To</label>
                                        <select
                                            className="bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm outline-none"
                                            value={editFormData.assignedTo}
                                            onChange={(e) => setEditFormData({ ...editFormData, assignedTo: e.target.value })}
                                            required
                                        >
                                            <option value="">Select member...</option>
                                            {members.map(member => (
                                                <option key={member._id} value={member._id}>
                                                    {member.name || member.email}
                                                </option>
                                            ))}
                                        </select>
                                    </div>
                                    <div className="flex gap-2 w-full sm:w-auto mt-2 sm:mt-0">
                                        <button type="submit" className="bg-blue-600 hover:bg-blue-500 px-4 py-2 rounded-lg font-bold text-sm transition-colors cursor-pointer flex-1">Save</button>
                                        <button type="button" onClick={() => setEditingTask(null)} className="bg-gray-700 hover:bg-gray-600 px-4 py-2 rounded-lg font-bold text-sm transition-colors cursor-pointer flex-1">Cancel</button>
                                    </div>
                                </form>
                            </div>
                        );
                    }

                    return (
                        <div
                            key={task._id}
                            className={`p-4 rounded-xl flex items-center justify-between border transition-all duration-300 group
                                ${isDone ? 'bg-gray-900/40 border-gray-800/50 opacity-60' : 'bg-gray-800/40 border-gray-700 hover:bg-gray-800/60'}
                            `}
                        >
                            <div className="flex items-center gap-4 cursor-pointer" onClick={() => handleToggleStatus(task)}>
                                <div className={`transition-all duration-300 ${isAnimating ? 'scale-125 text-green-400 animate-pulse' : ''}`}>
                                    {isDone ?
                                        <CheckCircle2 className="text-green-500" size={24} /> :
                                        <Circle className="text-gray-500 group-hover:text-blue-400 transition-colors" size={24} />
                                    }
                                </div>
                                <div>
                                    <p className={`font-medium transition-all duration-300 ${isDone ? 'line-through text-gray-500' : 'text-white'}`}>
                                        {task.title}
                                    </p>
                                    <div className="flex gap-3 mt-2">
                                        <span className={`text-[10px] uppercase tracking-wider font-bold px-2 py-0.5 rounded-full ${getPriorityColor(task.priority)} transition-all`}>
                                            {task.priority}
                                        </span>
                                        <span className={`flex items-center gap-1.5 text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full transition-colors
                                            ${isDone ? 'bg-green-500/20 text-green-400 border border-green-500/30' : 'bg-gray-700/50 text-gray-400'}
                                        `}>
                                            <Clock size={12} /> {task.status}
                                        </span>
                                        {task.assignedTo && typeof task.assignedTo === 'object' && (
                                            <span className="text-[10px] text-gray-500 uppercase tracking-wider bg-gray-800/80 px-2 py-0.5 rounded-full border border-gray-700">
                                                By: {task.assignedTo.name || task.assignedTo.email}
                                            </span>
                                        )}
                                    </div>
                                </div>
                            </div>

                            <div className="flex gap-2">
                                <button
                                    onClick={(e) => {
                                        e.stopPropagation();
                                        setEditingTask(task._id);
                                        setEditFormData({
                                            title: task.title,
                                            description: task.description,
                                            priority: task.priority,
                                            assignedTo: task.assignedTo?._id || ''
                                        });
                                    }}
                                    className="p-2 text-gray-600 hover:text-blue-400 hover:bg-blue-400/10 rounded-lg transition-colors opacity-0 group-hover:opacity-100 cursor-pointer"
                                    title="Edit Task"
                                >
                                    <Edit2 size={18} />
                                </button>
                                <button
                                    onClick={(e) => { e.stopPropagation(); handleDelete(task._id); }}
                                    className="p-2 text-gray-600 hover:text-red-400 hover:bg-red-400/10 rounded-lg transition-colors opacity-0 group-hover:opacity-100 cursor-pointer"
                                    title="Delete Task"
                                >
                                    <Trash2 size={18} />
                                </button>
                            </div>
                        </div>
                    );
                })}
                {displayTasks.length === 0 && !isLoading && (
                    <div className="text-center py-10 text-gray-500 border border-dashed border-gray-700 rounded-xl">
                        {tasks.length > 0 ? "You've hidden completed tasks! Clean board." : "No tasks yet. Create one to get started."}
                    </div>
                )}
            </div>
        </div>
    );
};

export default Tasks;